"use client";
import Link from "next/link";
import Navbar from "@/components/navbar";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using ListifyPH ("the Service"), you agree to be bound by these Terms & Conditions. If you do not agree with any part of these terms, you must not use the Service.

These Terms apply to all users including visitors, registered users, and paid subscribers.`,
  },
  {
    title: "2. Description of Service",
    content: "ListifyPH is an AI-powered property listing generator built specifically for real estate agents and developers in the Philippines. Using the Service, you can generate:",
    list: [
      "Professional property listing descriptions (SEO-optimised)",
      "Facebook posts with hooks and calls to action",
      "Facebook Ad copy in multiple variations",
      "Instagram captions with relevant hashtags",
      "Content in English and Filipino (Tagalog)",
    ],
  },
  {
    title: "3. User Accounts",
    content: "",
    list: [
      "You must provide accurate and complete information when creating an account",
      "You are solely responsible for maintaining the security of your account credentials",
      "One account per individual person — sharing accounts is not permitted",
      "You must be at least 18 years of age to create an account",
      "We reserve the right to suspend or terminate accounts that violate these Terms",
      "You must notify us immediately of any unauthorised access to your account",
    ],
  },
  {
    title: "4. Free Plan & Subscriptions",
    content: "",
    list: [
      "Free plan: 3 content generations per month, listing description only, English only",
      "Pro plan: ₱499/month — unlimited generations, all 4 content types, English + Filipino, all ad styles, full listing history",
      "Agency plan: ₱1,499/month — everything in Pro plus 5 team member seats and bulk generation",
      "All payments are processed securely by PayMongo",
      "Subscriptions renew automatically on a monthly billing cycle",
      "You may cancel your subscription at any time from your Settings page",
      "Cancellations take effect at the end of the current billing period",
      "We do not offer refunds for partial billing months",
    ],
  },
  {
    title: "5. Acceptable Use",
    content: "By using ListifyPH, you agree NOT to:",
    list: [
      "Use the Service for any unlawful purpose or in violation of Philippine law",
      "Generate false, misleading, or fraudulent property listings",
      "Resell or redistribute AI-generated content as part of a competing AI service",
      "Attempt to reverse engineer, decompile, or extract the underlying AI system or prompts",
      "Share, sell, or transfer your account credentials to another person",
      "Abuse the free plan limits through multiple accounts or automated sign-ups",
      "Upload or transmit malicious code, spam, or abusive content",
    ],
  },
  {
    title: "6. Intellectual Property",
    content: "",
    list: [
      "Content you generate using ListifyPH belongs to you — you own it and may use it freely",
      "ListifyPH retains all rights to the platform, interface, system prompts, and underlying technology",
      "The ListifyPH name, logo, and brand identity are our exclusive property",
      "You may not use our branding or imply endorsement by ListifyPH without written permission",
      "Your account data (name, email, listings) remains yours and can be exported on request",
    ],
  },
  {
    title: "7. AI-Generated Content Disclaimer",
    content: "Important limitations of AI-generated content:",
    list: [
      "All content is generated by AI (Claude by Anthropic) and may contain inaccuracies",
      "We do not guarantee the accuracy, completeness, or fitness of any generated content",
      "You are solely responsible for reviewing all content before publishing or using it",
      "Property details such as prices, sizes, and amenities should be independently verified",
      "ListifyPH is not liable for any errors, omissions, or misleading statements in AI-generated listings",
      "Do not publish generated content without your own review and professional judgment",
    ],
  },
  {
    title: "8. Payment Terms",
    content: "",
    list: [
      "All prices are quoted in Philippine Peso (₱) and are inclusive of applicable taxes",
      "Payments are accepted via PayMongo — supporting GCash, Maya, and major credit/debit cards",
      "Failed or declined payments may result in immediate downgrade to the Free plan",
      "We will notify you at least 30 days in advance of any price changes",
      "Disputed charges must be reported within 30 days of the billing date",
    ],
  },
  {
    title: "9. Limitation of Liability",
    content: "To the maximum extent permitted by applicable law, ListifyPH shall not be liable for:",
    list: [
      "Loss of business, revenue, profit, or anticipated savings",
      "Errors, inaccuracies, or omissions in AI-generated listing content",
      "Downtime or service interruptions from third-party providers (Supabase, Anthropic, Vercel)",
      "Data loss beyond our reasonable control, including force majeure events",
      "Any indirect, incidental, special, or consequential damages arising from your use of the Service",
    ],
  },
  {
    title: "10. Termination",
    content: "We reserve the right to suspend or terminate your account without prior notice if you:",
    list: [
      "Violate any provision of these Terms & Conditions",
      "Engage in fraudulent, abusive, or illegal activity",
      "Abuse the free plan limits or API access",
      "Provide false information during registration",
      "Engage in behaviour that harms other users or the integrity of the platform",
    ],
  },
  {
    title: "11. Governing Law",
    content: `These Terms & Conditions are governed by and construed in accordance with the laws of the Republic of the Philippines.

Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of Bacolod City, Negros Occidental, Philippines.`,
  },
  {
    title: "12. Contact Us",
    content: `If you have any questions about these Terms & Conditions, please reach out:

Joel B. Gacho
ListifyPH
Bacolod City, Negros Occidental, Philippines
joelgacho.ffseo@gmail.com

We will respond to all inquiries within 5 business days.`,
  },
];

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#050914", color: "#F0F4FF" }}>
      <Navbar />

      <main style={{ paddingTop: 120, paddingBottom: 100, padding: "120px 24px 100px" }}>
        <div style={{ maxWidth: 780, margin: "0 auto" }}>

          {/* Back link + header */}
          <div style={{ marginBottom: 56 }}>
            <Link href="/"
              style={{ display: "inline-flex", alignItems: "center", gap: 8, color: "#7A8BA8", fontSize: 13, textDecoration: "none", marginBottom: 32, transition: "color 0.2s" }}
              onMouseEnter={(e) => (e.currentTarget as HTMLElement).style.color = "#F0F4FF"}
              onMouseLeave={(e) => (e.currentTarget as HTMLElement).style.color = "#7A8BA8"}
            >
              ← Back to home
            </Link>
            <h1 className="font-syne" style={{ fontSize: "clamp(2rem, 4vw, 2.8rem)", fontWeight: 800, color: "#F0F4FF", letterSpacing: "-0.02em", marginBottom: 12 }}>
              Terms & Conditions
            </h1>
            <p style={{ fontSize: 14, color: "#7A8BA8" }}>Last updated: June 8, 2026</p>
          </div>

          {/* Callout */}
          <div style={{ background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.2)", borderRadius: 12, padding: "18px 22px", marginBottom: 52, fontSize: 14, color: "#7A8BA8", lineHeight: 1.75 }}>
            Please read these Terms carefully before using ListifyPH. By using our service you agree to these terms. If you have any questions, contact us at{" "}
            <a href="mailto:joelgacho.ffseo@gmail.com" style={{ color: "#3B82F6", textDecoration: "none" }}>joelgacho.ffseo@gmail.com</a>.
          </div>

          {/* Content sections */}
          <div style={{ display: "flex", flexDirection: "column", gap: 44 }}>
            {sections.map(({ title, content, list }) => (
              <section key={title}>
                <h2 className="font-syne" style={{ fontSize: "1.05rem", fontWeight: 700, color: "#3B82F6", marginBottom: 14, letterSpacing: "-0.01em" }}>
                  {title}
                </h2>
                {content && (
                  <p style={{ fontSize: 15, color: "#7A8BA8", lineHeight: 1.85, marginBottom: list ? 16 : 0, whiteSpace: "pre-line" }}>
                    {content}
                  </p>
                )}
                {list && (
                  <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10 }}>
                    {list.map((item) => (
                      <li key={item} style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
                        <span style={{ width: 6, height: 6, borderRadius: "50%", background: "#3B82F6", flexShrink: 0, marginTop: 9 }} />
                        <span style={{ fontSize: 15, color: "#7A8BA8", lineHeight: 1.75 }}>{item}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </section>
            ))}
          </div>

          <div style={{ height: 1, background: "linear-gradient(90deg,transparent,rgba(148,163,184,0.1) 30%,rgba(148,163,184,0.1) 70%,transparent)", margin: "64px 0 32px" }} />
          <p style={{ fontSize: 13, color: "#7A8BA8", textAlign: "center" }}>
            © 2026 ListifyPH ·{" "}
            <Link href="/privacy-policy" style={{ color: "#3B82F6", textDecoration: "none" }}>Privacy Policy</Link>
          </p>
        </div>
      </main>

      <PageFooter />
    </div>
  );
}

function PageFooter() {
  return (
    <footer className="dot-grid" style={{ background: "#030609", borderTop: "1px solid rgba(148,163,184,0.08)", position: "relative" }}>
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: "linear-gradient(90deg,#1D4ED8,#3B82F6)" }} />
      <div style={{ maxWidth: 1160, margin: "0 auto", padding: "48px 24px", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 24 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <img src="/logo.svg" alt="ListifyPH" style={{ height: 32, width: "auto" }} />
          <span style={{ color: "#7A8BA8", fontSize: 13 }}>— Write less. Sell more.</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 28 }}>
          {[
            { href: "/privacy-policy", label: "Privacy Policy" },
            { href: "/terms", label: "Terms" },
            { href: "mailto:joelgacho.ffseo@gmail.com", label: "Contact" },
          ].map(({ href, label }) => (
            <a key={label} href={href}
              style={{ fontSize: 13, color: "#7A8BA8", textDecoration: "none", transition: "color 0.2s" }}
              onMouseEnter={(e) => (e.target as HTMLElement).style.color = "#F0F4FF"}
              onMouseLeave={(e) => (e.target as HTMLElement).style.color = "#7A8BA8"}
            >{label}</a>
          ))}
        </div>
        <div style={{ fontSize: 13, color: "#7A8BA8" }}>© 2026 ListifyPH</div>
      </div>
    </footer>
  );
}
